#!/usr/bin/env -S uv run --script --quiet
# /// script
# requires-python = ">=3.11"
# ///
"""screenshot-purge — Age- and disk-pressure-based purge of UI test screenshots.

Browser-UI test runs land screenshots in <project_root>/reports/screenshots/
(per ~/.claude/rules/browser-ui-test-techniques.md §19). The folder is
gitignored, so anything written there is short-lived cache — never user work.

Two independent removal policies run on every fire:

1. **Age-based** (default policy):
   Any regular file with a known screenshot extension whose mtime exceeds
   `screenshot_max_age_hours` (default 72 h) is removed.

2. **Low-disk override**:
   If free space on the partition holding `reports/screenshots/` drops below
   `screenshot_lowdisk_min_free_gb` (default 5 GiB), the oldest screenshots
   are removed first (regardless of the 72 h cap) until free space recovers
   above `screenshot_lowdisk_target_free_gb` (default 10 GiB) OR no
   candidates remain. The hysteresis gap (min vs target) prevents the
   detector from oscillating right at the threshold.

Why mtime, not a folder-name timestamp:
   Unlike .trashcan/ batches — which encode their disposal moment in the
   folder name to defeat accidental `touch` — screenshots are written by
   test runners that already control mtime correctly, and there is no
   batch concept. mtime IS the canonical "when was this screenshot
   taken" signal.

Why screenshots bypass safe-delete / .trashcan/:
   Per ~/.claude/rules/use-safe-delete.md, test artefacts regenerated by
   the runner fall under "Yes, trivially recoverable" — they belong to
   plain `rm`, not `.trashcan/`. Pushing them through .trashcan/ would
   balloon it (the very thing the safe-delete rule warns against).

What this detector NEVER touches:
   - Any file whose extension is not a known screenshot type.
   - Symlinks (never followed, never unlinked).
   - The `reports/screenshots/` directory itself (kept alive even when
     empty — the next test run expects it to exist).
   - Anything outside `reports/screenshots/` (path traversal impossible —
     the root is resolved via state.project_root() and we glob inside it).
"""

from __future__ import annotations

import os
import shutil
import sys
import time
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "lib"))

import disk_pressure as dp  # noqa: E402  # S7 dual disk metric (TRDD-1T53EKTN)
import state  # noqa: E402

# Image extensions written by browser-UI test runners. Lowercase comparison.
_SCREENSHOT_EXTS = frozenset({".png", ".jpg", ".jpeg", ".webp", ".gif"})

# Files inside the screenshots dir that are STRUCTURAL (kept around even when
# empty) and must never be deleted. The dir itself stays as a directory.
_KEEP_FILES = frozenset({".gitkeep", "README.txt", "README.md"})

_GIB = 1024 * 1024 * 1024


def _is_screenshot(path: Path) -> bool:
    """True iff path is a regular file (not symlink) with a screenshot ext."""
    if path.is_symlink() or not path.is_file():
        return False
    if path.name in _KEEP_FILES:
        return False
    return path.suffix.lower() in _SCREENSHOT_EXTS


def _iter_screenshots(root: Path) -> Iterable[Path]:
    """Yield every screenshot file under root, recursive, deterministic order."""
    # rglob is recursive; sorted() forces a stable order for tests + logs.
    for p in sorted(root.rglob("*")):
        if _is_screenshot(p):
            yield p


def _free_bytes(path: Path) -> int:
    """Free bytes on the filesystem holding `path`. -1 on stat failure."""
    try:
        return shutil.disk_usage(path).free
    except OSError:
        return -1


def _fmt_size(bytes_: int) -> str:
    """Human-friendly size: B, KB, MB, GB."""
    if bytes_ < 1024:
        return f"{bytes_}B"
    if bytes_ < 1024 * 1024:
        return f"{bytes_ / 1024:.1f}KB"
    if bytes_ < _GIB:
        return f"{bytes_ / (1024 * 1024):.1f}MB"
    return f"{bytes_ / _GIB:.1f}GB"


def _fmt_age(seconds: int) -> str:
    """Short age: 4h12m, 3d4h, 12m, 45s."""
    if seconds < 60:
        return f"{seconds}s"
    if seconds < 3600:
        return f"{seconds // 60}m"
    if seconds < 86400:
        return f"{seconds // 3600}h{(seconds % 3600) // 60}m"
    return f"{seconds // 86400}d{(seconds % 86400) // 3600}h"


def _unlink_quietly(path: Path) -> int:
    """Unlink path, returning bytes freed (0 on failure)."""
    try:
        size = path.stat().st_size
    except OSError:
        size = 0
    try:
        path.unlink()
    except OSError as exc:
        state.log_line("screenshot-purge", f"failed to unlink '{path}': {exc}")
        return 0
    return size


def main() -> int:
    state.init_state()

    if not state.is_truthy_env("CLAUDE_PLUGIN_OPTION_SCREENSHOT_PURGE_ENABLED", True):
        return 0

    max_age_hours = state.coerce_int(
        os.environ.get("CLAUDE_PLUGIN_OPTION_SCREENSHOT_MAX_AGE_HOURS"), 72
    )
    lowdisk_min_gb = state.coerce_int(
        os.environ.get("CLAUDE_PLUGIN_OPTION_SCREENSHOT_LOWDISK_MIN_FREE_GB"), 5
    )
    lowdisk_target_gb = state.coerce_int(
        os.environ.get("CLAUDE_PLUGIN_OPTION_SCREENSHOT_LOWDISK_TARGET_FREE_GB"), 10
    )

    # Hysteresis guard: a misconfiguration where target <= min would cause
    # the loop to bail immediately. Force a minimum 1 GiB gap.
    if lowdisk_target_gb <= lowdisk_min_gb:
        lowdisk_target_gb = lowdisk_min_gb + 1

    threshold_sec = max_age_hours * 3600
    lowdisk_min_bytes = lowdisk_min_gb * _GIB
    lowdisk_target_bytes = lowdisk_target_gb * _GIB

    project_root = state.project_root()
    screenshots_dir = project_root / "reports" / "screenshots"
    if not screenshots_dir.is_dir():
        return 0

    now = int(time.time())

    # ----- Phase 1: age-based purge -----------------------------------------
    age_removed_count = 0
    age_removed_bytes = 0
    age_oldest_sec = 0

    for shot in _iter_screenshots(screenshots_dir):
        try:
            mtime = int(shot.stat().st_mtime)
        except OSError:
            continue
        age = now - mtime
        if age < threshold_sec:
            continue
        freed = _unlink_quietly(shot)
        if freed >= 0:
            age_removed_count += 1
            age_removed_bytes += freed
            if age > age_oldest_sec:
                age_oldest_sec = age
            state.log_line(
                "screenshot-purge",
                f"age-purged '{shot.relative_to(project_root)}' "
                f"(age: {_fmt_age(age)}, size: {_fmt_size(freed)})",
            )

    # ----- Phase 2: low-disk override --------------------------------------
    lowdisk_removed_count = 0
    lowdisk_removed_bytes = 0
    free_before = _free_bytes(screenshots_dir)
    free_after = free_before

    if free_before >= 0 and free_before < lowdisk_min_bytes:
        # Build a list of remaining screenshots, oldest first by mtime.
        remaining: list[tuple[int, Path]] = []
        for shot in _iter_screenshots(screenshots_dir):
            try:
                remaining.append((int(shot.stat().st_mtime), shot))
            except OSError:
                continue
        remaining.sort(key=lambda t: t[0])  # oldest first

        for mtime, shot in remaining:
            free_after = _free_bytes(screenshots_dir)
            if free_after < 0 or free_after >= lowdisk_target_bytes:
                break
            age = now - mtime
            freed = _unlink_quietly(shot)
            if freed >= 0:
                lowdisk_removed_count += 1
                lowdisk_removed_bytes += freed
                state.log_line(
                    "screenshot-purge",
                    f"lowdisk-purged '{shot.relative_to(project_root)}' "
                    f"(age: {_fmt_age(age)}, size: {_fmt_size(freed)})",
                )
        # Refresh after the loop so the output line reports the post-state.
        free_after = _free_bytes(screenshots_dir)

    # ----- Reporting --------------------------------------------------------
    if age_removed_count > 0:
        print(
            f"[screenshot-purge] removed {age_removed_count} screenshot(s) "
            f"from reports/screenshots/ older than {max_age_hours}h "
            f"(oldest: {_fmt_age(age_oldest_sec)}, freed {_fmt_size(age_removed_bytes)})."
        )

    if lowdisk_removed_count > 0:
        if free_before >= 0 and free_after >= 0:
            disk_note = (
                f"free space {_fmt_size(free_before)} → {_fmt_size(free_after)}"
            )
        else:
            disk_note = "free-space probe failed"
        # S7 (TRDD-1T53EKTN): also report the DUAL metric — writable-only numbers
        # contradict the OS UI (writable+purgeable) and mislead the human reading this.
        print(
            f"[screenshot-purge] LOW DISK: removed {lowdisk_removed_count} "
            f"oldest screenshot(s) to relieve pressure "
            f"(freed {_fmt_size(lowdisk_removed_bytes)}, {disk_note}; "
            f"{dp.disk_pressure(screenshots_dir).label})."
        )

    state.rotate_log_if_big("screenshot-purge")
    return 0


if __name__ == "__main__":
    sys.exit(main())
