"""AppArmor / SELinux profile-gap security patterns.

Wave-33 distillation round 19, angle: AppArmor / SELinux Profile Gaps.

Catalogue of 9 LSM-profile-gap patterns distilled in
`reports/distill-round-19/selinux-apparmor-profile-gaps.md`. Targets
host-level SELinux config, setsebool postinst scripts, audit2allow .te
files, AppArmor mode-switch CLI calls, systemd units, Docker security-opt
custom types, libapparmor C API calls, Kubernetes securityContext absence,
and Dockerfile RUN layers.

What is NOT here (already shipped — DO NOT duplicate):

  * Container runtime `--security-opt apparmor=unconfined` / `seccomp=unconfined` /
    `label=disable` — `container_runtime_patterns.py` rule `cre-runtime-lsm-unconfined`.
  * Docker Compose `security_opt: [apparmor:unconfined, label:disable]` —
    `sandbox_escape_patterns.py` rule `container-compose-seccomp-unconfined`.
  * K8s `appArmorProfile.type: Unconfined` / `seccompProfile.type: Unconfined`
    (structured 1.30+ API) — `sandbox_escape_patterns.py` rule `k8s-securitycontext-gap`.
  * `docker run --privileged` — `container_runtime_patterns.py` `cre-runtime-privileged-flag`.
  * polkit `.rules` permissive — `linux_privesc_patterns.py`.

What IS here (9 net-new rules, regex-only, all RE2-safe):

  * sa-selinux-host-config-permissive              (CRITICAL)
  * sa-setsebool-persistent-high-risk              (HIGH)
  * sa-audit2allow-wildcard-allow                  (HIGH)
  * sa-apparmor-complain-mode-in-script            (HIGH)
  * sa-systemd-apparmor-profile-name               (MEDIUM)
  * sa-docker-selinux-custom-permissive-type       (MEDIUM)
  * sa-libapparmor-change-to-unconfined            (CRITICAL)
  * sa-k8s-securitycontext-no-lsm-profile          (MEDIUM)
  * sa-dockerfile-runcmd-aa-complain               (HIGH)

Public surface:

  * Rule(id, name, severity, description, pattern, owasp_asi)
  * RULES — ordered tuple of every rule.
  * scan_text(text) -> list[Finding]
  * Finding(rule_id, line, column, matched_text, severity, description,
            owasp_asi)

OWASP ASI mapping used:
  ASI-02 — Secret / capability leak (libapparmor unconfined API call)
  ASI-05 — Security Misconfiguration (all LSM profile gaps)

All regexes are RE2-compatible (no backreferences, no lookbehind, no
catastrophic backtracking shapes). Patterns are PRE-COMPILED at module
load. Fail-fast: callers receive structured Finding tuples, never raised
exceptions on benign input.
"""

from __future__ import annotations

import re
from typing import NamedTuple

# ---- Data model ---------------------------------------------------------


class Finding(NamedTuple):
    """A single rule match."""

    rule_id: str
    line: int
    column: int
    matched_text: str
    severity: str
    description: str
    owasp_asi: str


class Rule(NamedTuple):
    """A compiled detection rule."""

    id: str
    name: str
    severity: str
    description: str
    pattern: re.Pattern  # type: ignore[type-arg]
    owasp_asi: str


# ---- Pre-compiled patterns -----------------------------------------------

# SAG-01: /etc/selinux/config or Ansible selinux module with permissive/disabled
# Three shapes: (a) bare config key, (b) Ansible state: value, (c) sed/echo rewrite
_SAG01 = re.compile(
    r"(?:^SELINUX=(?:permissive|disabled)\s*$"
    r"|\bstate:\s*(?:permissive|disabled)\b"
    r"|(?:sed\s[^;|&\n]{0,100}|echo\s[^;|&\n]{0,100})SELINUX=(?:permissive|disabled)\b)",
    re.MULTILINE,
)

# SAG-02: setsebool -P with a dangerous boolean set to on/1/true
_SAG02 = re.compile(
    r"\bsetsebool\s+-P\s+"
    r"(?:allow_exec(?:heap|mem|stack)|httpd_exec(?:mem|cgi)|"
    r"ssh_sysadm_login|container_manage_cgroup|allow_domain_fd_use)"
    r"\s+(?:1|on|true)\b",
    re.MULTILINE,
)

# SAG-03: audit2allow wildcard allow rule in .te policy files
# Two shapes: (a) wildcard { * } permission set, (b) broad resource type + dangerous perms
_SAG03 = re.compile(
    r"(?:^\s*allow\s+\S+\s+\S+:\S+\s+\{\s*\*\s*\}"
    r"|^\s*allow\s+\S+\s+(?:file_type|fs_type|domain|unlabeled_t)\s*:\s*"
    r"(?:file|process|dir)\s+\{[^}]{0,200}(?:execute|write)\b"
    r"|#\s*Generated by audit2allow\b)",
    re.MULTILINE,
)

# SAG-04: aa-complain mode-switch in shell/Ansible (not Dockerfile-specific RUN)
# Two shapes: (a) shell aa-complain <arg>, (b) Ansible state: complain
_SAG04 = re.compile(
    r"(?:\baa-complain\s+\S+"
    r"|\bstate:\s*complain\b)",
    re.MULTILINE,
)

# SAG-05: AppArmorProfile= directive in systemd unit
_SAG05 = re.compile(
    r"^\s*AppArmorProfile\s*=\s*.+",
    re.MULTILINE,
)

# SAG-06: Docker --security-opt label:type= with permissive type, or K8s legacy annotation
_SAG06 = re.compile(
    r"(?:--security-opt\s+label:type=(?:unconfined_t|spc_t|svirt_t|initrc_t)\b"
    r"|container\.apparmor\.security\.beta\.kubernetes\.io/[^:]+:\s*unconfined\b)",
    re.MULTILINE,
)

# SAG-07: libapparmor C API call with "unconfined" as target hat/profile
_SAG07 = re.compile(
    r'\baa_change_(?:hat|onexec|profile)\s*\([^)]{0,200}"unconfined"',
    re.MULTILINE,
)

# SAG-08: K8s securityContext with hardening fields but no seccompProfile/appArmorProfile
# Two-pass: anchor detects a securityContext block containing hardening fields;
# the window check (absence) is done in scan_text logic below.
_SAG08_ANCHOR = re.compile(
    r"\bsecurityContext:\s*\n(?:[ \t]+\S[^\n]*\n){0,40}"
    r"[ \t]+(?:allowPrivilegeEscalation|runAsNonRoot|readOnlyRootFilesystem)\b",
    re.MULTILINE,
)
_SAG08_LSM_PRESENT = re.compile(
    r"\b(?:seccompProfile|appArmorProfile)\b",
)

# SAG-09: Dockerfile RUN layer calling aa-complain, or entrypoint path-anchored aa-complain
_SAG09 = re.compile(
    r"(?:^\s*RUN\s+[^\n]{0,200}\baa-complain\b"
    r"|\baa-complain\s+/etc/apparmor\.d/\S+)",
    re.MULTILINE,
)


# ---- Helper --------------------------------------------------------------


def _line_col(text: str, pos: int) -> tuple[int, int]:
    """Return (1-based line, 1-based column) for a byte offset in *text*."""
    line = text.count("\n", 0, pos) + 1
    last_nl = text.rfind("\n", 0, pos)
    col = pos - last_nl  # last_nl is -1 when pos is on line 1 → col = pos + 1
    return line, col


# ---- Rule table ----------------------------------------------------------

RULES: tuple[Rule, ...] = (
    Rule(
        id="sa-selinux-host-config-permissive",
        name="SELinux host config permissive or disabled",
        severity="CRITICAL",
        description=(
            "SELINUX=permissive or SELINUX=disabled in /etc/selinux/config, "
            "Ansible selinux module state, or a sed/echo rewrite of the config file. "
            "Removes mandatory access control from the host; a container breakout has "
            "no LSM barrier."
        ),
        pattern=_SAG01,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-setsebool-persistent-high-risk",
        name="setsebool -P flipping high-risk boolean",
        severity="HIGH",
        description=(
            "setsebool -P enabling a dangerous SELinux boolean (allow_exec*, "
            "httpd_exec*, ssh_sysadm_login, container_manage_cgroup, "
            "allow_domain_fd_use). Persists across reboots and expands the attack "
            "surface: allow_execstack/heap negate ASLR/DEP host-wide; "
            "container_manage_cgroup enables cgroup v1 namespace escape."
        ),
        pattern=_SAG02,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-audit2allow-wildcard-allow",
        name="audit2allow generated policy with wildcard allow rule",
        severity="HIGH",
        description=(
            "SELinux .te policy file with a wildcard permission set { * }, an "
            "overly broad resource type (file_type/fs_type/domain) combined with "
            "execute or write, or the audit2allow generator header comment. "
            "Auto-generated policy committed without review negates SELinux's purpose."
        ),
        pattern=_SAG03,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-apparmor-complain-mode-in-script",
        name="AppArmor aa-complain mode-switch in postinst or Ansible script",
        severity="HIGH",
        description=(
            "aa-complain <profile> call in a shell/postinst script or Ansible "
            "apparmor module with state: complain. Sets the named profile to log-only "
            "mode (equivalent to SELINUX=permissive per profile). Should never appear "
            "in production CI/CD or packaging scripts."
        ),
        pattern=_SAG04,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-systemd-apparmor-profile-name",
        name="AppArmorProfile= directive in systemd unit",
        severity="MEDIUM",
        description=(
            "AppArmorProfile= in a systemd [Service] section. If the named profile "
            "is absent from the kernel, systemd silently starts the service without "
            "confinement. Surfaces units for review to confirm the profile is "
            "actually loaded."
        ),
        pattern=_SAG05,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-docker-selinux-custom-permissive-type",
        name="Docker --security-opt label:type= set to permissive SELinux type",
        severity="MEDIUM",
        description=(
            "Docker --security-opt label:type=unconfined_t/spc_t/svirt_t/initrc_t "
            "or Kubernetes legacy annotation container.apparmor.security.beta.kubernetes.io "
            "set to 'unconfined'. unconfined_t and spc_t are functionally equivalent "
            "to label:disable for MAC purposes."
        ),
        pattern=_SAG06,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-libapparmor-change-to-unconfined",
        name="libapparmor API call targeting unconfined hat/profile",
        severity="CRITICAL",
        description=(
            "aa_change_hat(), aa_change_onexec(), or aa_change_profile() called "
            "with \"unconfined\" as the target. Drops all AppArmor confinement from "
            "the calling process. No legitimate production use for a confined service "
            "or plugin sandbox."
        ),
        pattern=_SAG07,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-k8s-securitycontext-no-lsm-profile",
        name="Kubernetes securityContext present but missing both LSM profile fields",
        severity="MEDIUM",
        description=(
            "A Kubernetes securityContext block contains allowPrivilegeEscalation, "
            "runAsNonRoot, or readOnlyRootFilesystem but does NOT contain "
            "seccompProfile or appArmorProfile within the same 40-line window. "
            "Without these fields the runtime uses the node default, which is absent "
            "on containerd/CRI-O nodes."
        ),
        pattern=_SAG08_ANCHOR,
        owasp_asi="ASI-05",
    ),
    Rule(
        id="sa-dockerfile-runcmd-aa-complain",
        name="Dockerfile RUN layer or entrypoint activating aa-complain",
        severity="HIGH",
        description=(
            "Dockerfile RUN instruction invoking aa-complain, or a shell entrypoint "
            "script calling aa-complain /etc/apparmor.d/<profile>. Bakes AppArmor "
            "profile downgrade into the image layer; runs at container startup and "
            "can affect other containers on the same node sharing the profile."
        ),
        pattern=_SAG09,
        owasp_asi="ASI-05",
    ),
)


# ---- Scanner -------------------------------------------------------------


def scan_text(text: str) -> list[Finding]:
    """Scan *text* for all LSM profile-gap patterns and return sorted findings.

    Findings are deduplicated by (rule_id, line, column) and sorted by
    (line, column, rule_id). The two-pass SAG-08 rule emits a finding only
    when the matched securityContext window does NOT contain seccompProfile
    or appArmorProfile.
    """
    seen: set[tuple[str, int, int]] = set()
    findings: list[Finding] = []

    for rule in RULES:
        if rule.id == "sa-k8s-securitycontext-no-lsm-profile":
            # Two-pass: anchor match + absence of LSM fields in a 40-line window
            # starting from the securityContext: line.  The anchor regex ends at the
            # first hardening field, but seccompProfile/appArmorProfile may appear
            # AFTER that field in the same block — so we extend the window to 40
            # lines from the anchor start.
            for m in rule.pattern.finditer(text):
                # Collect up to 40 lines from the start of the match
                block_start = m.start()
                # Walk forward up to 40 newlines from the start
                pos = block_start
                for _ in range(40):
                    idx = text.find("\n", pos)
                    if idx == -1:
                        pos = len(text)
                        break
                    pos = idx + 1
                window = text[block_start:pos]
                if _SAG08_LSM_PRESENT.search(window):
                    continue  # LSM profile present — not a gap
                line, col = _line_col(text, m.start())
                key = (rule.id, line, col)
                if key in seen:
                    continue
                seen.add(key)
                findings.append(
                    Finding(
                        rule_id=rule.id,
                        line=line,
                        column=col,
                        matched_text=m.group(0)[:120],
                        severity=rule.severity,
                        description=rule.description,
                        owasp_asi=rule.owasp_asi,
                    )
                )
        else:
            for m in rule.pattern.finditer(text):
                line, col = _line_col(text, m.start())
                key = (rule.id, line, col)
                if key in seen:
                    continue
                seen.add(key)
                findings.append(
                    Finding(
                        rule_id=rule.id,
                        line=line,
                        column=col,
                        matched_text=m.group(0)[:120],
                        severity=rule.severity,
                        description=rule.description,
                        owasp_asi=rule.owasp_asi,
                    )
                )

    findings.sort(key=lambda f: (f.line, f.column, f.rule_id))
    return findings
