#!/usr/bin/env -S uv run --script --quiet
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""agent_context_bench — measure what `agent_config_patterns.scan_text` actually CATCHES.

WHY this exists (janitor#226), and what its numbers may honestly claim:

`scan_text` guards the files a coding agent auto-loads AS INSTRUCTIONS (project memory,
skill/agent definitions, tool manifests). Every test and fix on it so far has been about the
detector FIRING CORRECTLY — severity mismatches, the dead `_reportable` filter, false
positives on prohibition text. All real, all plumbing. **Nobody had measured whether the rules
catch a poisoning attempt the author did not already have in mind.**

The asymmetry is what makes this worth a benchmark rather than more unit tests:

  * a FALSE POSITIVE costs one human read and is reported loudly (janitor#167, twice);
  * a FALSE NEGATIVE is silent BY CONSTRUCTION — a poisoned file no rule matches produces a
    clean heartbeat, which is byte-identical to a clean repo. The detector's whole value is
    the case nobody notices.

**The corpus must be authored BLIND or the measurement is worthless.** Patterns written and
graded against the same examples measure nothing but their author's consistency. This corpus
was generated by an external model (llm-externalizer, free pool) that was given the attack
classes BY INTENT ONLY — no regex, no trigger literal, not even this repo's phrasing. If a
future contributor extends the corpus, extend it the same way: describe the ATTACK, never the
pattern. A first run scoring >95% is the tell that the blindness broke.

What the numbers mean, precisely:

  * `recall_intended` — the sample's own class rule fired. This is the honest headline: it is
    the rule that CLAIMS this class doing its job.
  * `recall_any` — some rule fired. Weaker but real: the file would still have been surfaced
    to a human, just under a different name. Reported separately because conflating the two
    would let a rule set take credit for accidents.
  * `false_positive_rate` — benign samples that fired anything. Benign samples are scanned as
    `prose`, which runs EVERY rule: the worst case on purpose, so the FP number is an upper
    bound rather than a flattering one.
  * out-of-claim classes (in the corpus, not in RULES) are the declared BLIND SPOTS. A miss
    there is not a defect — it is the scope boundary being honest. An incidental hit is a
    bonus, never a promise.

CLAIMED classes are read from `agent_config_patterns.RULES` at runtime, never hardcoded, so a
newly added rule joins the measured set automatically and a deleted one cannot leave a stale
claim behind.

Exit status: 0 when the run matches the baseline, 1 on any regression (recall down, or FP up).
READ-ONLY — it never edits a file, and the corpus is JSONL rather than on-disk markdown so
these payloads can never be mistaken for real agent-context files by a scanner or a reader.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS / "lib"))

import agent_config_patterns as acp  # noqa: E402

_REPO = _SCRIPTS.parent
DEFAULT_CORPUS = _REPO / "tests" / "agent_context_bench" / "corpus.jsonl"
DEFAULT_BASELINE = _REPO / "tests" / "agent_context_bench" / "baseline.json"


def claimed_rule_ids() -> set[str]:
    """The classes the rule set CLAIMS to cover — derived from the code, never a copy of it.

    janitor#226 asked for the claim to be written down because it was implicit in the
    patterns. Deriving it here keeps it written down and TRUE: a hardcoded list would be a
    second source of truth that drifts the first time someone adds a rule.
    """
    return {r.id for r in acp.RULES}


def load_corpus(path: Path) -> list[dict]:
    """Parse the JSONL corpus, skipping unparseable lines rather than dying.

    The corpus is machine-generated by a free-pool model, so a truncated or malformed line is
    an expected operational reality, not a corruption. Dropping it loses one sample; aborting
    would lose the whole measurement. The count of dropped lines is reported, because a
    silently shrinking corpus would make recall look better every time generation degraded.
    """
    samples, dropped = [], 0
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            dropped += 1
            continue
        if isinstance(rec, dict) and rec.get("content") and rec.get("label"):
            samples.append(rec)
        else:
            dropped += 1
    if dropped:
        print(f"note: {dropped} corpus line(s) unparseable and skipped", file=sys.stderr)
    return samples


def split_of(sample: dict) -> str:
    """Deterministic `dev` / `holdout` assignment, keyed on the sample's own content.

    This exists to keep the measurement honest AFTER someone starts improving the rules.
    Tuning a pattern until it passes the corpus that revealed its gap turns recall from a
    measure of generalisation into a measure of fit — the same "author and grade in one pass"
    error janitor#226 was filed about, just committed one step later. So: tune on `dev`,
    quote the number from `holdout`.

    Keyed on a content hash rather than a counter so the split is stable when the corpus grows
    or is reordered — a sample cannot drift from holdout into dev (which would silently leak
    the thing being held out).
    """
    digest = hashlib.sha256(sample["content"].encode("utf-8")).hexdigest()
    return "dev" if int(digest[:8], 16) % 2 == 0 else "holdout"


def score(samples: list[dict]) -> dict:
    """Run every sample through `scan_text` and tally recall / false positives.

    `file_kind` is taken from the sample, never guessed here, because it changes WHICH rules
    run at all: `source` deliberately skips the injection + authority rules (they fire
    constantly inside code comments), so scanning a poisoned instruction file as `source`
    would understate recall, and scanning a code sample as `prose` would overstate it.
    """
    claimed = claimed_rule_ids()
    per_class: dict[str, dict] = {}
    fp_samples: list[dict] = []
    per_population: dict[str, dict] = {}
    benign_total = 0

    for s in samples:
        label = s["label"]
        kind = s.get("kind") or ("source" if label in _SOURCE_CLASSES else "prose")
        fired = {f.rule_id for f in acp.scan_text(s["content"], file_kind=kind, filename="")}

        # Any `benign*` label is a control. They are kept as SEPARATE populations because a
        # single blended rate hides the actual finding: `benign` samples were deliberately
        # chosen to sit near the danger zone (security policies, post-mortems, fixtures) and
        # measure the WORST CASE, while `benign-ordinary` is everyday project code and
        # measures what a typical repo would see. Averaging them would produce a number that
        # describes neither, and which population you sampled would silently set the result.
        if label.startswith("benign"):
            benign_total += 1
            by_pop = per_population.setdefault(label, {"n": 0, "fp": 0})
            by_pop["n"] += 1
            if fired:
                by_pop["fp"] += 1
                fp_samples.append({"id": s.get("id", ""), "fired": sorted(fired),
                                   "note": s.get("note", ""), "population": label})
            continue

        bucket = per_class.setdefault(
            label, {"claimed": label in claimed, "n": 0, "intended": 0, "any": 0, "misses": []}
        )
        bucket["n"] += 1
        if label in fired:
            bucket["intended"] += 1
        if fired:
            bucket["any"] += 1
        else:
            bucket["misses"].append(s.get("note", s.get("id", "")))

    claimed_n = sum(b["n"] for b in per_class.values() if b["claimed"])
    claimed_hit = sum(b["intended"] for b in per_class.values() if b["claimed"])
    claimed_any = sum(b["any"] for b in per_class.values() if b["claimed"])

    return {
        "totals": {
            "samples": len(samples),
            "benign": benign_total,
            "attack_claimed": claimed_n,
            "recall_intended": round(claimed_hit / claimed_n, 4) if claimed_n else 0.0,
            "recall_any": round(claimed_any / claimed_n, 4) if claimed_n else 0.0,
            # None, NEVER 0.0, when no benign sample was measured. "0% false positives" off an
            # empty benign population is the single most flattering thing this tool could
            # print, and it would be indistinguishable from a genuinely clean result.
            "false_positive_rate": (
                round(len(fp_samples) / benign_total, 4) if benign_total else None
            ),
        },
        "per_population": per_population,
        "per_class": per_class,
        "false_positives": fp_samples,
        "unclaimed_rules": sorted(claimed - set(per_class)),
    }


# Classes whose natural home is a CODE file. Kept beside the scorer (not in the corpus
# generator) so a corpus that omits an explicit `kind` still scores under the right rule
# subset — see `score` for why the distinction is not cosmetic.
_SOURCE_CLASSES = {
    "mcp-annotation-lying", "mcp-schema-in-annotations", "whole-env-exfil",
    "worm-self-propagation", "crypto-clipper-triad", "procmem-credential-extraction",
    "git-protocol-only-dependency", "dns-exfil-long-subdomain", "two-step-code-injection",
}


def render(res: dict) -> str:
    t = res["totals"]
    out = [
        "# agent-context-integrity — rule coverage (janitor#226)",
        "",
        f"samples {t['samples']} · attack(claimed) {t['attack_claimed']} · benign {t['benign']}",
        f"**recall (intended rule) {t['recall_intended']:.0%}** · recall (any rule) "
        f"{t['recall_any']:.0%} · false positives "
        + (
            "UNMEASURED (no benign samples)"
            if t["false_positive_rate"] is None
            # With more than one benign population the blended rate is an artefact of how
            # many of each were authored, not a property of the detector — it would move if
            # someone simply wrote more ordinary samples. Point at the table instead of
            # printing a number that describes neither population.
            else "per population, see below"
            if len(res.get("per_population") or {}) > 1
            else f"{t['false_positive_rate']:.0%}"
        ),
        "",
    ]
    pops = res.get("per_population") or {}
    if pops:
        out += ["", "| benign population | n | flagged | FP |", "|---|---|---|---|"]
        for name, p in sorted(pops.items()):
            rate = p["fp"] / p["n"] if p["n"] else 0.0
            out.append(f"| `{name}` | {p['n']} | {p['fp']} | {rate:.0%} |")
    out += [
        "",
        "| class | claimed | n | intended | any |",
        "|---|---|---|---|---|",
    ]
    for name, b in sorted(res["per_class"].items(), key=lambda kv: (not kv[1]["claimed"], kv[0])):
        out.append(
            f"| `{name}` | {'yes' if b['claimed'] else 'NO (blind spot)'} | {b['n']} "
            f"| {b['intended']} | {b['any']} |"
        )
    if res["unclaimed_rules"]:
        out += ["", "**Rules with no corpus coverage** (untested claims): "
                + ", ".join(f"`{r}`" for r in res["unclaimed_rules"])]
    if res["false_positives"]:
        out += ["", "## False positives"] + [
            f"- `{fp['fired']}` — {fp['note']}" for fp in res["false_positives"]
        ]
    return "\n".join(out) + "\n"


def compare(cur: dict, base: dict) -> tuple[bool, list[str]]:
    """Regression gate: recall may never fall and false positives may never rise.

    Deliberately asymmetric to the corpus growing: adding samples changes the denominators, so
    this compares RATES, not counts. A corpus that grows and holds its rate is an improvement;
    one that grows while the rate drops is a real regression and should fail.
    """
    problems = []
    if cur.get("split", "all") != base.get("split", "all"):
        # Comparing a dev run against an all-corpus baseline compares two different
        # populations and would report a rate change that is pure population difference.
        # Refusing is the only safe answer: a gate that silently compares the wrong two
        # numbers is worse than no gate.
        return False, [
            f"split mismatch: run is {cur.get('split', 'all')!r}, "
            f"baseline is {base.get('split', 'all')!r} — regenerate the baseline for this split"
        ]
    # PER-CLASS, not aggregate. The aggregate rate moves whenever the corpus GAINS a class,
    # because a new class has its own difficulty — so comparing totals reports "recall fell"
    # for a corpus that merely got harder, with no code change at all. That happened on the
    # first extension (25% -> 23% purely from adding two low-scoring classes). A gate that
    # cries regression when someone improves the corpus is a gate people learn to override,
    # which costs every real regression it would ever have caught.
    #
    # So: compare only classes present in BOTH runs, where a drop CAN only mean the rules got
    # worse. Classes new to this run are reported as information, never as failure.
    cur_classes, base_classes = cur.get("per_class", {}), base.get("per_class", {})
    for name, cb in sorted(base_classes.items()):
        cc = cur_classes.get(name)
        if not cc or not cb["n"] or not cc["n"]:
            continue
        was, now = cb["intended"] / cb["n"], cc["intended"] / cc["n"]
        if now < was:
            problems.append(f"{name}: recall fell {was:.0%} -> {now:.0%}")
    # The FP rate stays an AGGREGATE comparison: unlike recall, its denominator is the benign
    # population alone, which does not change when an attack class is added — so a rise here
    # really is a rise.
    c, b = cur["totals"], base["totals"]
    if (
        c["false_positive_rate"] is not None
        and b["false_positive_rate"] is not None
        and c["false_positive_rate"] > b["false_positive_rate"]
    ):
        problems.append(
            f"false_positive_rate rose {b['false_positive_rate']:.0%} -> "
            f"{c['false_positive_rate']:.0%}"
        )
    return (not problems), problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    ap.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    ap.add_argument("--write-baseline", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument(
        "--split",
        choices=("all", "dev", "holdout"),
        default="all",
        help="measure one half only. Tune on dev; quote holdout. See split_of().",
    )
    args = ap.parse_args()

    if not args.corpus.exists():
        print(f"corpus not found: {args.corpus}", file=sys.stderr)
        return 2

    samples = load_corpus(args.corpus)
    if args.split != "all":
        samples = [s for s in samples if split_of(s) == args.split]
    res = score(samples)
    res["split"] = args.split
    print(json.dumps(res, indent=2) if args.json else render(res), end="")

    if args.write_baseline:
        args.baseline.parent.mkdir(parents=True, exist_ok=True)
        args.baseline.write_text(json.dumps(res, indent=2) + "\n", encoding="utf-8")
        print(f"\nbaseline written: {args.baseline}")
        return 0

    if args.baseline.exists():
        ok, problems = compare(res, json.loads(args.baseline.read_text(encoding="utf-8")))
        if not ok:
            print("\nREGRESSION:\n" + "\n".join(f"  - {p}" for p in problems), file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
