#!/usr/bin/env -S uv run --script --quiet
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate every artifact derived from `design/specs/issue-codes.toml` (TRDD-DSN035UN, card C10).

    build_issue_codes.py --write    # regenerate the three artifacts
    build_issue_codes.py --check    # exit 1, naming each stale file, if regeneration would change it
    build_issue_codes.py            # print docs/ISSUE-CODES.md to stdout

Artifacts: scripts/memgrep/src/rules_gen.rs (ONLY rows whose emitter is "memgrep" — their severity
fits the frozen Rust `Rule.sev: Severity`), scripts/lib/issue_codes_gen.py (EVERY row), and
docs/ISSUE-CODES.md. The TOML is the single source of truth; the three are DERIVED, so a hand edit
is overwritten and `--check` fails the moment one drifts.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve().parent
ROOT = _HERE.parent
sys.path.insert(0, str(_HERE / "lib"))

import tickets  # noqa: E402

SPEC = ROOT / "design" / "specs" / "issue-codes.toml"
RULES_RS = ROOT / "scripts" / "memgrep" / "src" / "rules_gen.rs"
LIB_PY = ROOT / "scripts" / "lib" / "issue_codes_gen.py"
DOC_PATH = ROOT / "docs" / "ISSUE-CODES.md"

SOURCE_LINE = "GENERATED by scripts/build_issue_codes.py from design/specs/issue-codes.toml — do not edit."
SEVERITY_VARIANT = {"ERROR": "Error", "WARN": "Warn", "INFO": "Info"}
FIX_VARIANT = {"safe": "Safe", "unsafe": "Unsafe", "none": "NoFix"}
PY_FIELDS = ("code", "name", "family", "severity", "fix", "gate_floor", "emitter", "summary", "why", "fix_text", "kind", "what")


def load() -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    with SPEC.open("rb") as fh:
        data = tomllib.load(fh)
    return sorted(data["issue"], key=lambda r: r["code"]), sorted(data.get("retired", []), key=lambda r: r["code"])


def _rs(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t") + '"'


def render_rust(rows: list[dict[str, Any]]) -> str:
    out = [f"//! {SOURCE_LINE}", "#![allow(dead_code)] // until C20 wires RULES", "use crate::lint_rules::{Fix, Rule};", "use crate::memory::Severity;", "pub(crate) const RULES: &[Rule] = &["]
    for r in rows:
        if r["emitter"] != "memgrep":
            continue
        out.append(
            f"    Rule {{ code: {_rs(r['code'])}, name: {_rs(r['name'])}, family: {_rs(r['family'])}, sev: Severity::{SEVERITY_VARIANT[r['severity']]}, "
            f"fix: Fix::{FIX_VARIANT[r['fix']]}, gate_floor: {str(r['gate_floor']).lower()}, summary: {_rs(r['summary'])} }},"
        )
    out.append("];")
    return "\n".join(out) + "\n"


def render_python(rows: list[dict[str, Any]], retired: list[dict[str, str]]) -> str:
    out = [
        f"# {SOURCE_LINE}",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class IssueCode:",
    ]
    for f in PY_FIELDS:
        if f == "gate_floor":
            out.append("    gate_floor: bool")
        elif f in ("kind", "what"):
            out.append(f'    {f}: str = ""')
        else:
            out.append(f"    {f}: str")
    out += ["", "", "ISSUE_CODES: tuple[IssueCode, ...] = ("]
    for r in rows:
        args = ", ".join(f"{f}={r[f]!r}" for f in PY_FIELDS if f in r)
        out.append(f"    IssueCode({args}),")
    out += [")", "", "RETIRED: dict[str, str] = {"]
    out += [f"    {r['code']!r}: {r['reason']!r}," for r in retired]
    out.append("}")
    return "\n".join(out) + "\n"


HEADER = """# Janitor issue codes

**Generated from `design/specs/issue-codes.toml` — do not edit by hand.**
Regenerate with `uv run scripts/build_issue_codes.py --write`; a test fails if this file drifts.

Every issue the janitor's scanners and validators can detect has a stable code, `<SCANNER>-<NNN>`.
A code is **immutable once shipped** (like a schema version): never renumbered, never reused — so a
citation in a closed ticket, a report, or a TRDD still resolves years later.

A code decides **who may fix it**, and that is the load-bearing property of this table:

| Domain | What it is | What the janitor does |
|---|---|---|
| **HARNESS** | the janitor's OWN machinery — its index, its migrations, its daemon, its state | opens a ticket and **dispatches a repair agent automatically**. It is fixing itself; nobody else owns that machinery and the blast radius is its own regeneratable state. |
| **PROJECT** | the USER's code, repo, workflows, rulesets | **proposes only.** It authors a proposal TRDD under `design/proposals/` and recommends the exact command. Running `/janitor-support-open-ticket TRDD-<id>` **is** the approval — until then nothing is dispatched and nothing is touched. |

The domain comes from the code, not from the finding's text, so a detector cannot grant itself
unattended access to your repository.
"""

FOOTER = """
## How a finding becomes work

A detector raises a code — that is the entire producer-side API:

```python
raise_issue("WFSEC-001", where="ci.yml:42", evidence=[".github/workflows/ci.yml"])
```

`raise_issue` looks the code up, renders **our** template with the detector's **sanitized** data, and
routes by domain: a HARNESS code opens a ticket the scheduler will dispatch; a PROJECT code writes a
proposal TRDD and hands back the approval command.

Ticket text is treated as **untrusted data**, never instructions: values interpolated from filenames,
dependency names, workflow lines, and issue titles are defanged on ingest (a payload cannot mimic a
`[janitor-…]` marker), and the dispatched agent's instructions come from the janitor's own skills —
never from the ticket.

## Inspecting the queue

```
/janitor-support-tickets              # the queue, with severity, attempts, and budget
/janitor-support-open-ticket TRDD-…   # approve a proposed PROJECT fix
```
"""


def _cell(s: str) -> str:
    return s.replace("|", "\\|")


def render_doc(rows: list[dict[str, Any]]) -> str:
    catalog = [r for r in rows if "kind" in r]
    by_domain: dict[str, list[dict[str, Any]]] = {tickets.HARNESS: [], tickets.PROJECT: []}
    for r in catalog:
        by_domain[tickets.KIND_REGISTRY[r["kind"]].domain].append(r)

    out = [HEADER]
    for domain, heading in ((tickets.HARNESS, "HARNESS — the janitor repairs itself (automatic)"), (tickets.PROJECT, "PROJECT — your repo (proposed, never automatic)")):
        group = by_domain[domain]
        out.append(f"\n## {heading}\n")
        out.append(f"{len(group)} code(s).\n")
        out.append("| Code | Scanner | Severity | Issue |")
        out.append("|---|---|---|---|")
        for r in group:
            out.append(f"| `{r['code']}` | {r['emitter'].split(':', 1)[1]} | {r['severity'].lower()} | {_cell(r['summary'])} |")
        out.append("")
        for r in group:
            out.append(f"### `{r['code']}` — {r['summary']}\n")
            out.append(f"- **Scanner:** `{r['emitter'].split(':', 1)[1]}` · **Severity:** `{r['severity'].lower()}` · **Kind:** `{r['kind']}`")
            out.append(f"- **What it is:** {r['what']}")
            out.append(f"- **Why it matters:** {r['why']}")
            out.append(f"- **Fix attempted:** {r['fix_text']}\n")

    out.append(f"\n## All codes by family\n\n{len(rows)} code(s) across every emitter.\n")
    for fam in sorted({r["family"] for r in rows}):
        out.append(f"### {fam}\n")
        out.append("| Code | Severity | Fix | Emitter | Summary |")
        out.append("|---|---|---|---|---|")
        for r in rows:
            if r["family"] == fam:
                out.append(f"| `{r['code']}` | {r['severity']} | {r['fix']} | {r['emitter']} | {_cell(r['summary'])} |")
        out.append("")

    out.append(FOOTER)
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="build_issue_codes")
    ap.add_argument("--write", action="store_true", help="regenerate the derived files")
    ap.add_argument("--check", action="store_true", help="exit 1 if any derived file is stale")
    args = ap.parse_args(argv)

    rows, retired = load()
    targets = {RULES_RS: render_rust(rows), LIB_PY: render_python(rows, retired), DOC_PATH: render_doc(rows)}
    if args.write:
        for path, text in targets.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
        print(f"wrote {len(targets)} files ({len(rows)} codes)")
        return 0
    if args.check:
        stale = [p for p, t in targets.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print(f"STALE: {p} — run `uv run scripts/build_issue_codes.py --write`")
        if not stale:
            print("ok")
        return 1 if stale else 0
    print(targets[DOC_PATH], end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
