#!/usr/bin/env -S uv run --script --quiet
# /// script
# requires-python = ">=3.11"
# ///
"""generate_integrity_manifest — write .integrity/manifest-sha256.json.

The self-integrity manifest is a RELEASE ARTIFACT: a sha256 hash of every
file on the plugin's prompt-instruction surface (README, CLAUDE.md, every
SKILL.md, command + rule markdown — DEFAULT_MANIFEST_GLOBS). The
`janitor-self-integrity` heartbeat detector compares the INSTALLED plugin's
live files against this baseline and surfaces a drift line on any
mutated/missing/extra file — so a tampered or stale install cannot silently
feed the assistant rewritten instructions. WITHOUT a shipped manifest the
detector is a permanent no-op (`if not _MANIFEST_PATH.is_file(): return None`);
this generator is what gives it a baseline to verify against.

WHY a generator instead of a hand-maintained file: a hand-edited manifest
drifts the instant any globbed file changes, which would make the detector
cry wolf on every clean install. So the manifest is regenerated by
`publish.py` (Step 10.5) on EVERY release, AFTER the version bump + changelog
so it matches the exact tree that ships, and staged into the release commit.
It is therefore always fresh per release and never hand-maintained. The
manifest globs (README/CLAUDE/skills/commands/rules) are NOT touched by the
version bump (which only edits plugin.json + __version__ in *.py) or the
git-cliff changelog regen (CHANGELOG.md is not globbed), so the manifest is
self-consistent with the committed release tree.

The manifest never includes itself: DEFAULT_MANIFEST_GLOBS does not match
`.integrity/manifest-sha256.json`, so adding the manifest to the tree can
never make the detector report it as an `extra` file.

Modes:
  (default)    compute + write `<root>/.integrity/manifest-sha256.json`,
               print a one-line summary.
  --dry-run    compute + print "would write N file(s)" — write NOTHING, so a
               `publish.py --dry-run` exercises the generator end-to-end
               without dirtying the working tree.
  --root PATH  plugin root to hash (default: auto-resolved from this script's
               own location — `<plugin>/scripts/generate_integrity_manifest.py`
               → `<plugin>`). `publish.py` passes the resolved plugin root
               explicitly; tests pass a throwaway fixture tree.

Fail-fast: the compute/write helpers raise on an unexpected I/O error and the
exception propagates (non-zero exit), so a broken manifest aborts the publish
rather than shipping a silent integrity gap.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# This script lives at `<plugin-root>/scripts/generate_integrity_manifest.py`,
# so the plugin root is ONE level above the script's own directory. (The
# sibling detector at scripts/detectors/ is two levels above its file — the
# extra `detectors/` segment is why; do not copy that `.parent.parent` here.)
_HERE = Path(__file__).resolve().parent
_PLUGIN_ROOT = _HERE.parent
sys.path.insert(0, str(_HERE / "lib"))

from janitor_self_integrity import (  # type: ignore[import-not-found]  # noqa: E402
    DEFAULT_MANIFEST_GLOBS,
    compute_manifest,
    write_manifest,
)

# Kept in sync with the detector's `_MANIFEST_PATH` (scripts/detectors/
# janitor-self-integrity.py) — both reference `.integrity/manifest-sha256.json`
# under the plugin root. A change here MUST change there too, or the generator
# writes a manifest the detector never reads.
_MANIFEST_REL = Path(".integrity") / "manifest-sha256.json"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the janitor self-integrity file-hash manifest.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute the manifest and report the file count, but write nothing.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Plugin root to hash (default: auto-resolved from this script's location).",
    )
    args = parser.parse_args()

    root = (args.root if args.root is not None else _PLUGIN_ROOT).resolve()
    manifest = compute_manifest(root, DEFAULT_MANIFEST_GLOBS)
    count = len(manifest)

    if args.dry_run:
        print(
            f"[generate-integrity-manifest] DRY-RUN — would write {count} "
            f"file hash(es) to {_MANIFEST_REL.as_posix()}"
        )
        return 0

    write_manifest(manifest, root / _MANIFEST_REL)
    print(
        f"[generate-integrity-manifest] wrote {count} file hash(es) to "
        f"{_MANIFEST_REL.as_posix()}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
