#!/usr/bin/env -S uv run --script --quiet
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Thin entry point kept for the old command: `docs/ISSUE-CODES.md` is now generated by
`build_issue_codes.py` from `design/specs/issue-codes.toml` (TRDD-DSN035UN). Same flags: --write, --check."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_issue_codes  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(build_issue_codes.main())
